
# Subscription / naming


variable "subscription_id" {
  description = "Azure subscription ID to deploy into. Leave null in CI and supply ARM_SUBSCRIPTION_ID instead."
  type        = string
  default     = null
}

variable "product" {
  description = "HMCTS product name, used as the first element of every resource name."
  type        = string
  default     = "hmcts-devtest"

  validation {
    condition     = can(regex("^[a-z0-9-]{2,20}$", var.product))
    error_message = "product must be 2-20 characters of lowercase letters, digits or hyphens."
  }
}

variable "component" {
  description = "Component within the product, used as the second element of every resource name."
  type        = string
  default     = "backend"

  validation {
    condition     = can(regex("^[a-z0-9-]{2,20}$", var.component))
    error_message = "component must be 2-20 characters of lowercase letters, digits or hyphens."
  }
}

variable "environment" {
  description = "Deployment environment. Drives naming, tagging and resilience defaults."
  type        = string
  default     = "prod"

  validation {
    condition     = contains(["dev", "test", "stg", "prod"], var.environment)
    error_message = "environment must be one of: dev, test, stg, prod."
  }
}

variable "location" {
  description = "Azure region for all resources. UK South by default, to keep data in the UK."
  type        = string
  default     = "uksouth"
}

variable "common_tags" {
  description = "Additional tags merged over the tags generated by this configuration."
  type        = map(string)
  default     = {}
}

variable "cost_centre" {
  description = "Cost centre code used for chargeback reporting."
  type        = string
  default     = "dts-devops-test"
}

variable "business_area" {
  description = "HMCTS business area that owns the service."
  type        = string
  default     = "cft"
}


# PostgreSQL Flexible Server


variable "postgres_version" {
  description = "Major version of PostgreSQL to run."
  type        = string
  default     = "16"
}

variable "postgres_sku_name" {
  description = "SKU for the flexible server, e.g. GP_Standard_D2ds_v5 or B_Standard_B1ms."
  type        = string
  default     = "GP_Standard_D2ds_v5"
}

variable "postgres_storage_mb" {
  description = "Provisioned storage for the flexible server, in megabytes."
  type        = number
  default     = 32768

  validation {
    condition     = var.postgres_storage_mb >= 32768
    error_message = "postgres_storage_mb must be at least 32768 (32 GiB)."
  }
}

variable "postgres_backup_retention_days" {
  description = "Number of days automated backups are retained."
  type        = number
  default     = 14

  validation {
    condition     = var.postgres_backup_retention_days >= 7 && var.postgres_backup_retention_days <= 35
    error_message = "postgres_backup_retention_days must be between 7 and 35."
  }
}

variable "postgres_geo_redundant_backup_enabled" {
  description = "Whether backups are replicated to the Azure paired region."
  type        = bool
  default     = true
}

variable "postgres_high_availability_enabled" {
  description = "Whether to run a zone-redundant standby. Requires a General Purpose or Memory Optimized SKU."
  type        = bool
  default     = true
}

variable "database_name" {
  description = "Name of the application database created on the flexible server."
  type        = string
  default     = "devtest"
}

variable "db_admin_username" {
  description = "Administrator login for the flexible server. The password is generated, never supplied."
  type        = string
  default     = "dbadmin"

  validation {
    condition     = !contains(["azure_superuser", "azure_pg_admin", "admin", "administrator", "root", "guest", "public"], lower(var.db_admin_username))
    error_message = "db_admin_username must not be a reserved PostgreSQL or Azure login name."
  }
}

variable "db_allowed_ip_ranges" {
  description = "Map of firewall rule name to start/end IP, for operator access to the database. Empty by default."
  type = map(object({
    start_ip_address = string
    end_ip_address   = string
  }))
  default = {}
}


# Container image / registry


variable "container_registry_login_server" {
  description = "Login server of the registry holding the application image, e.g. hmctspublic.azurecr.io."
  type        = string
  default     = "hmctspublic.azurecr.io"
}

variable "container_registry_id" {
  description = "Resource ID of the container registry, used to grant AcrPull to the app identity. Null skips the role assignment."
  type        = string
  default     = null
}

variable "container_image_name" {
  description = "Repository path of the application image within the registry."
  type        = string
  default     = "hmcts/test-backend"
}

variable "container_image_tag" {
  description = "Immutable image tag to deploy. Supplied by the pipeline as sha-<short sha>; never 'latest'."
  type        = string
  default     = "latest"

  validation {
    condition     = length(trimspace(var.container_image_tag)) > 0
    error_message = "container_image_tag must not be empty."
  }
}


# Container App


variable "container_port" {
  description = "Port the application listens on inside the container."
  type        = number
  default     = 4000
}

variable "container_cpu" {
  description = "vCPU allocated to each replica. Must pair with container_memory per Container Apps rules."
  type        = number
  default     = 1.0
}

variable "container_memory" {
  description = "Memory allocated to each replica, e.g. 2Gi. Must be 2x the vCPU value."
  type        = string
  default     = "2Gi"
}

variable "min_replicas" {
  description = "Minimum number of replicas. At least 2 in production to survive a node drain."
  type        = number
  default     = 2
}

variable "max_replicas" {
  description = "Maximum number of replicas the HTTP autoscaler may scale out to."
  type        = number
  default     = 10
}

variable "http_concurrent_requests_per_replica" {
  description = "Concurrent requests per replica before the HTTP scale rule adds another replica."
  type        = number
  default     = 100
}

variable "ingress_external_enabled" {
  description = "Whether ingress is reachable from the internet. Set false when fronted by APIM or Front Door."
  type        = bool
  default     = true
}


# Observability


variable "log_retention_days" {
  description = "Retention period for the Log Analytics workspace, in days."
  type        = number
  default     = 90

  validation {
    condition     = var.log_retention_days >= 30 && var.log_retention_days <= 730
    error_message = "log_retention_days must be between 30 and 730."
  }
}
